Updated deploy-book.yml to stop if any of the python scripts error, added baseurl to config

diff --git a/.github/workflows/deploy-book.yml b/.github/workflows/deploy-book.yml
--- a/.github/workflows/deploy-book.yml
+++ b/.github/workflows/deploy-book.yml
@@ -42,16 +42,32 @@ jobs:
         cd python/docs-examples
         for f in *.py; do python "$f"; done
         cd ../..
-
-    # Build the book
-    - name: Build the book
+   
+   # New additions:     
+  - name: Run external scripts
+  run: |
+    set -e  # Fail immediately if any script errors
+    cd python/docs-examples
+    for f in *.py; do python "$f"; done
+    cd ../..
+    
+        # Build the book
+  - name: Build the book
       run: |
         jupyter-book build docs/
+        
+        
+  - name: GitHub Pages action
+  uses: peaceiris/actions-gh-pages@v3
+  with:
+    github_token: ${{ secrets.GITHUB_TOKEN }}
+    publish_dir: docs/_build/html
+
 
     # Push the book's HTML to github-pages
-    - name: GitHub Pages action
-      uses: peaceiris/actions-gh-pages@v3.8.0
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: docs/_build/html
+  #  - name: GitHub Pages action
+  #    uses: peaceiris/actions-gh-pages@v3.8.0
+  #    with:
+  #      github_token: ${{ secrets.GITHUB_TOKEN }}
+  #      publish_dir: docs/_build/html
         
